[project]
name = "cherubim-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.142.1",
    "numpy>=2.4.6",
    "pandas>=3.0.6",
    "pydantic>=2.13.5",
    "python-dateutil>=2.9.0.post0",
    "uvicorn[standard]>=0.54.0",
]

[project.scripts]
cherubim-backend = "cherubim_backend:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
